# Frontend local Docker Compose stack.

name: ${COMPOSE_PROJECT_NAME:-nijigen-video-site-frontend}

services:

  # This is only used to set correct permission for node_modules and pnpm store for web service
  # Because those node-modules and pnpm store files are saved during image creation (Dockerfile), so need to use the same image as what `web` is using
  web-init:
    extends:
      file: ../../infra/compose/common-dev-services.yml
      service: web-pnpm-base
    profiles:
      - frontend
    user: "0:0"
    environment:
      HOST_UID: "${HOST_UID:?HOST_UID must be provided}"
      HOST_GID: "${HOST_GID:?HOST_GID must be provided}"
    entrypoint:
      - sh
      - -ceu
    command:
      - |
        mkdir -p \
          /workspace/frontend/node_modules \
          /workspace/frontend/web/node_modules \
          /pnpm/store
        chown -R "${HOST_UID}:${HOST_GID}" \
          /workspace/frontend/node_modules \
          /workspace/frontend/web/node_modules \
          /pnpm/store
    volumes:
      - frontend-node-modules:/workspace/frontend/node_modules
      - web-node-modules:/workspace/frontend/web/node_modules
      - frontend-pnpm-store:/pnpm/store

  web:
    extends:
      file: ../../infra/compose/common-dev-services.yml
      service: web-pnpm-base
    profiles:
      - frontend
    depends_on:
      api:
        condition: service_started
      web-init:
        condition: service_completed_successfully
    user: "${HOST_UID:?HOST_UID must be provided}:${HOST_GID:?HOST_GID must be provided}"
    entrypoint:
      - pnpm
    command:
      - --filter
      - web
      - dev
      - --host
      - 0.0.0.0
    ports:
      - ${FRONTEND_HTTP_PORT:-5173}:3000
    volumes:
      - ../../frontend:/workspace/frontend
      - frontend-node-modules:/workspace/frontend/node_modules
      - web-node-modules:/workspace/frontend/web/node_modules
      - frontend-pnpm-store:/pnpm/store

### Backend Part ###
# Just a simple replicate from the backend side compose.yml file

  api:
    extends:
      file: ../../infra/compose/common-dev-services.yml
      service: api-gradle-base
    ports:
      - ${API_HTTP_PORT:-18080}:8080

  postgres:
    extends:
      file: ../../infra/compose/common-services.yml
      service: postgres-base

  redis:
    extends:
      file: ../../infra/compose/common-services.yml
      service: redis-base

  flyway:
    extends:
      file: ../../infra/compose/common-services.yml
      service: flyway-base
    environment:
      FLYWAY_LOCATIONS: filesystem:/flyway/sql/baseline,filesystem:/flyway/sql/local
    volumes:
      - ../../infra/flyway/sql/local:/flyway/sql/local:ro

volumes:
  frontend-node-modules:
  web-node-modules:
  frontend-pnpm-store:
  postgres-data:
  redis-data:
